# Install the base requirements for the app.
# This stage is to support development.
FROM python:alpine AS base
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM node:alpine AS app-zip-creator
WORKDIR /app
COPY app .
RUN yarn install && \
    yarn run test && \
    rm -rf node_modules
RUN apk add zip && \
    zip -r /app.zip /app

# Do the actual build of the mkdocs site
FROM base AS build
COPY . .
#Adjusts file and folder to pt-br
RUN mv mkdocs_pt-br.yml mkdocs.yml && \
    mv docs_pt-br docs
RUN mkdocs build

# Extract the static content from the build
# and use a nginx image to serve the content
FROM nginx:alpine
COPY --from=app-zip-creator /app.zip /usr/share/nginx/html/assets/app.zip
COPY --from=build /app/site /usr/share/nginx/html